# This is a basic workflow to help you get started with Actions
name: pre-commit

on:
  pull_request:
  push:
    branches: [homework1]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
    - uses: pre-commit/isort@v2.0.0
    - uses: pre-commit/black@v2.0.0
