# This is a basic workflow to help you get started with Actions
name: pre-commit

on:
  pull_request:
  push:


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
    - uses: jamescurtin/isort-action@master
      with:
        requirementsFiles: "requirements.txt requirements-test.txt"
        args: ". --profile black --check"
    - uses: psf/black@stable
      with:
        args: ". --check"
